config/routes.rb
QAndAMachine::Engine.routes.draw do
  resources :assertions
end

app/models/q_and_a_machine/assertion.rb
module QAndAMachine
  class Assertion < ActiveRecord::Base
    after_create :enqueue

    def enqueue
      ::Resque.enqueue( AssertionProcessor, id )
    end
  end
end

app/models/q_and_a_machine/assertion_processor.rb
module QAndAMachine
  class AssertionProcessor
    @queue = :assertions

    def self.perform( assertion_id )
      assertion = Assertion.find( assertion_id )

      # feed assertion's data to ReVerb, put ReVerb's output back into the assertion record
      external_processor = IO.popen( "java -Xmx512m -jar lib/reverb.jar", 'w+' )
      external_processor.print assertion.assertion
      external_processor.close_write
      external_processor_output = external_processor.gets.chomp!.split( "\t" )

      assertion.arg1 = external_processor_output[2]
      assertion.relationship = external_processor_output[3]
      assertion.arg2 = external_processor_output[4]
      assertion.confidence = external_processor_output[11]
      assertion.arg1_normalized = external_processor_output[15]
      assertion.relationship_normalized = external_processor_output[16]
      assertion.arg2_normalized = external_processor_output[17]

      assertion.save!
    end
  end
end

app/controllers/q_and_a_machine/application_controller.rb
module QAndAMachine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/q_and_a_machine/assertions_controller.rb
module QAndAMachine
  class AssertionsController < ApplicationController
    def index
      @assertions = QAndAMachine::Assertion.all
    end

    def new
      @assertion = QAndAMachine::Assertion.new
    end

    def create 
      @assertion = QAndAMachine::Assertion.create(params[:assertion])
      flash[:notice] = 'Assertion has been created!'
      redirect_to @assertion
    end

    def show
      @assertion = QAndAMachine::Assertion.find(params[:id])
    end
  end
end

app/helpers/assertions_helper.rb
module AssertionsHelper
end

app/helpers/q_and_a_machine/application_helper.rb
module QAndAMachine
  module ApplicationHelper
  end
end

app/views/q_and_a_machine/assertions/_form.html.erb
<%= form_for @assertion do |f| %>
    <p>
      <%= f.label :assertion %>
      <%= f.text_field :assertion %>
    </p>
    <%= f.submit %>
<% end %>

app/views/q_and_a_machine/assertions/index.html.erb
<h1>Questions</h1>
<%= link_to "New Assertion", new_assertion_path %>
<% if @assertions.empty? %>
    There are currently no assertions.
<% else %>
    <table id='assertions'>
      <thead>
        <tr> <td>Subject</td> </tr>
      </thead>
      <tbody>
      <% @assertions.each do |assertion| %>
          <tr> <td id='assertion_assertion'><%= link_to assertion.assertion, assertion %></td> </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/q_and_a_machine/assertions/new.html.erb
<h1>New Assertion</h1>
<%= render 'form' %>

app/views/q_and_a_machine/assertions/show.html.erb
<% div_for @assertion do %>
    <h1><%= @assertion.assertion %></h1>
<% end %>

app/views/q_and_a_machine/questions/index.html.erb
<h1>Questions</h1>
<%= link_to "New Question", new_question_path %>
<% if @questions.empty? %>
    There are currently no questions.
<% else %>
    <table id='questions'>
      <thead>
        <tr> <td>Subject</td> </tr>
      </thead>
      <tbody>
      <% @questions.each do |question| %>
          <tr> <td id='question_question'><%= link_to question.question, question %></td> </tr>
      <% end %>
      </tbody>
    </table>
<% end %>